### ISSUE TITLE
Reintroduce Message Selectors

### ISSUE THREAD

**Issue by leostera** [riot-ml/riot#73]
In the past the `receive ()` expression could take a message selector function that acted as a way of a filter to decide whether a message was interesting at this time or not. This helped build the _selective receive_ functionality that we see in Erlang, Elixir, or Gleam.

Once reintroduced, selective receives on Riot could look like:

```ocaml
let selector msg = 
  match msg with
  | My_message -> `select `My_message
  | _ -> `skip
in

match receive ~selector () with
| `My_message -> (* act on message *)
```

Notice 2 things:

1. the receive expression now returns only messages of the types selected by the `selector` function, so we can make those functions total / exhaustive without a catch-all case
2. the selector is simply a function

**Comment by leostera** [comment]
Closed with #72

**Comment by FraMecca** [comment]
is any of this documented? I get build failures after upgrading to the last version

**Comment by leostera** [comment]
Hi @FraMecca! The API changes are reflected in the interface at the moment, so you should find a receive and a new receive_any function that does not take a selector as parameter and you can use to keep your build working.
